### ISSUE TITLE
Changing action space representation in robomimic environments

### ISSUE THREAD

**Issue by kbkartik** [ARISE-Initiative/robomimic#130]
Hi,

I want to run a standard behavior cloning policy using images (top-down view). How do we change rotation representation of the action space, say from axis angle to 6D rotation? I think by default for lift_ph task, the action space dimension is 7.

Thanks!

**Comment by amandlek** [comment]
There's a few steps that come to mind:
1. Expose an option in the underlying robosuite environment(s) or write a thin wrapper, that can take in 6D rotation actions and convert them to axis-angle before passing them to the step function.
2. Write a script to process the existing demonstration actions in the hdf5 from axis-angle to 6D rotation - this should be simple since you just need to switch representations and then rewrite the actions in the hdf5. 
3. You should also overwrite the environment metadata stored in the hdf5 and update possible the [environment name and kwargs](https://robomimic.github.io/docs/modules/environments.html#environments) to be consistent with the environment you created in step (1) so that the correct environment will be loaded during training.

**Comment by kbkartik** [comment]
For step3, what args are dependent on the action space representation? The way I see it, by default, the lift environment uses axis-angle representation. So when I create an env using the default robomimic env_kwargs, I don't have to change anything and it leads to the correct env being loaded right?

I think I have to only execute steps 1 and 2. Step 1 when I eval rollouts in the simulation env and step 2 when I do standard BC.

Am I missing something?

**Comment by amandlek** [comment]
If you create a new environment (e.g. subclass of Lift or some other robosuite environment, or add some kwarg that allos swapping the action space from axis-angle to some other rotation representation) in step (1), then you want to make sure that this environment is loaded during policy evaluations that take place in the training process. That's what I mean by step (3).

**Comment by kbkartik** [comment]
Just to get some more clarity, I believe I don't have to worry about step3. As per my original plan, I still want to evaluate in the environment using the original axis-angle formulation. Hence, I don't have to change any kwargs before loading a new lift environment.

1) During the standard BC, since the agent doesn't interact with the simulator, I just have to convert the hdf5 action representations from axis-angle to euler angle repr. This will allow my NN to learn to output in euler angle repr space. (STEP 2)

2) During eval before the agent steps into the env, I convert the action output from the NN based on euler angle repr into axis-angle repr which is what the env wants. (STEP 1)

3) You're right though that if I indeed choose to evaluate in a modified lift env where the default rotation repr isn't axis-angle, then I need to figure out if new mod env is being loaded properly.

Am I correct in my understanding wrt above points?

Many Thanks!

**Comment by amandlek** [comment]
Yes I believe so.
