### ISSUE TITLE
Problem when testing trained agent

### ISSUE THREAD

**Issue by AaronCaoZJ** [ARISE-Initiative/robomimic#152]
I am trying to learn imitation learning for robots, and I have tried to train an agent using **_diffusion_policy_** which was able to achieve a success rate of up to **_0.96_** when Rollout on the **_NutAssemblySquare_** task. I'm considering whether the agent has the ability to insert the nut into a target peg whose position has been changed, such as when I try to modify the coordinates of the peg in the `pegs_arena.xml` file.

In my practice, I move all the pegs to the left by some distance, however, from the trajectory during rollout, it seems that the robot **_still puts the nut into the original peg position without adapting to the change in the environment_**, which is supposed to be inconsistent with the effect of imitation learning.

 I would like to know if it is reasonable for me to adjust the test environment in this way, is it the case that such a modification does not change the Obs? If there is a correct way, please guide me, thanks!

**Comment by amandlek** [comment]
This is likely because (1) the agent never saw any variation in peg location in the training data and (2) the peg location is not given to the agent as an observation. This is likely a better question for the [robosuite](https://github.com/ARISE-Initiative/robosuite) issues page, but I would start by modifying the environment to include peg information as an observation - you can see an example [here](https://github.com/NVlabs/mimicgen_environments/blob/45db4b35a5a79e82ca8a70ce1321f855498ca82c/mimicgen_envs/envs/robosuite/nut_assembly.py#L316).
