### ISSUE TITLE
Split mask error for dataset multi-human (mh) task transport

### ISSUE THREAD

**Issue by hwjiang1510** [ARISE-Initiative/robomimic#54]
Hi,

I found that the data split for task transport of the dataset multi-human is wrong.

The dataset contains 300 demos in total. And it should contain 100, 100, and 100 demos for quality worse, okay, and better, respectively. However, when I check the data, I found for each quality, only 50 demos are included in the mask.

Moreover, the mask with multiple qualities is also incorrect. For example, the mask 'okay_better' should include all demos with quality okay and better (theoretically there should be 200 demos). However, the current split only includes 50 demos.

**Comment by amandlek** [comment]
The appendix of the robomimic [paper](https://arxiv.org/pdf/2108.03298.pdf) (section B.1) has more details on this - since the Transport task required two human operators, the multi-human datasets consist of all pairings between better, okay, and worse operators. Sorry for the confusion!

![image](https://user-images.githubusercontent.com/7931299/216262686-fdaa8159-20e0-492e-bf98-17c1a4040151.png)
