### ISSUE TITLE
The gripper cannot open when we use the trained model on the can and our own tasks.

### ISSUE THREAD

**Issue by dzy666fly** [ARISE-Initiative/robomimic#76]
Hi, it's me again! Thank you so much for sharing the source code and datasets. 
When I use trained BC-RNN model to test can-real (as designed in the paper) and stack-two-cubes (we design) tasks, we are so excited to see that the robot arm can pick up the can or the one cube and place them on the target position well, while to our confusion, the gripper cannot open when the can is on the target position or the one cube is on the other.
So how could we solve this problem? Thank you so much. 
The code below is the demo action of gripper on three tasks: can-real (the paper), can-real (ours), stack-two-cubes (ours).
'''
dp1 = './datasets/can_real/ph/image.hdf5'
dp2 = './datasets/demos_can_disk/image_v0.hdf5'
dp3 = './datasets/demos_stack_two_lower_closing_gripper/image_v1.hdf5'

f1, f2, f3 = h5py.File(dp1, 'r'), h5py.File(dp2, 'r'), h5py.File(dp3, 'r')

a1, a2, a3 = f1["data/demo_19/actions"][:,-1], f2["data/demo_19/actions"][:,-1], f3["data/demo_19/actions"][:,-1]
print(a1)
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.
  1.  1.]
print(a2)
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
print(a3)
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.]
'''

**Comment by amandlek** [comment]
It's a little hard to understand what might be going wrong for your particular setup, since there can be significant differences with respect to the real robot hardware and code infrastructure. However, I would first suggest validating your data by playing back your demonstration trajectories open-loop (e.g. with the `playback_dataset.py` script with the `--use-actions` flag) to verify your real robot environment actually respects the gripper open commands at the end of the trajectory, and that the data trajectories are high-quality enough to reproduce the intended motion (for the most part). If this works, then the problem is likely on the model training side and you could try some other tricks (e.g. collecting more data samples with the gripper open at the end of each trajectory, or re-weighting the samples in the dataset during training to pay more attention to the ones where the gripper is open, to account for dataset imbalance).
